jupyter-book/thebe

- README.md
- example/README.md
- example/index.html
This PR requires configuring the repo to use github-pages, served from the master branch.
> Add links to live demo and minor wording improvements in the description and example

- src/thebelab.js
if no inPrompt is present in the cell
> Added the possibility of skipping cells

- examples/activate_button.html
- examples/activate_button.js
@nthiery Could you have a look at this example? I am not sure what (or if anything) should go into thebelab, or if it should just stay in the example directory. Non of those features seem very specific, but I think Nicolas wanted to have some standartized activate button.
> Added an activate button example

- package.json
> chore(package): update @jupyterlab/outputarea to version 0.13.1

- src/thebelab.js
I don't know if this could be sensibly merged with the splitCell function and keeping both functions as easy as possible.
> Added function that splits at output promt.

- src/thebelab.js
so you have a handle on the kernel.
> return kernel promise from bootstrap

- examples/demo-active-variation.html
- examples/demo-active.html
- examples/demo-static.html
- examples/demo-with-thebelab.html
- examples/demo.html
- examples/index.html
To be beta tested at the workshop today. Later we will want to make a screencast out of it.
> Add step-by-step demo

- examples/index.html
- examples/widgets.html
- src/loader.js
- src/thebelab.js
I am also cleaning up the loading of custom widgets.
> Add custom widget example

- src/thebelab.js
Fixes #69 
Seems to work fine. (Adding a restart button next to the run.)
> Add restart button

- webpack.config.js
> Use generic jquery

- docs/conf.py
cc @minrk I think this is preventing the docs from building
> removing yaml from docs build

- webpack.config.js
Fix #188
The PR restores full jQuery to ensure full compatibility with jQuery UI.
> Restore complete jQuery for full compatibility with jQuery UI (i.e. sliders use animations)

- README.md
The contributing link didn't work!
> Fix contributing doc link in README.md

- .github/workflows/test.yml
linter was passing even if there were diffs
> make lint fail on diff

- docs/Makefile
- docs/conf.py
- docs/contribute.md
I had to remind myself how to use sphinx, I have been working in JS land for far too long apparently.
Thought this might be helpful for pointers to other people onboarding from that world.
I also updated a few of the pointers and `ThebeLab` --> `Thebe`
> Documentation updates for building the docs.

- development.html
- package.json
- disable caching in server so it actually gets new versions
- add cells for things that tend to fail (latex, widgets)
- add example config for testing with a local server for much faster turnaround
> improvements to development.html

- docs/examples/ipyleaflet_example.rst
- docs/index.rst
- docs/ipyleaflet_example.rst
This is basically a copy paste of Jason's #262 for pythreejs, except I've changed relevant portions to instead be about ipyleaflet. The `index.rst` file might end up conflicting but I'm not 100% sure.
> Documentation page with ipyleaflet example

- docs/configure.rst
follow-up to #274 
could @Miniland1333 or @moorepants confirm that these instructions are correct?
> 📚 DOCS: add read-only docs

- docs/examples/bqplot_example.rst
- docs/index.rst
> Add bqplot documentation

- CHANGELOG.md
Very minor fix to the PR link in the changelog.
> Maintain: Minor fix to link in changelog

- .github/workflows/npm-publish.yml
- .github/workflows/test.yml
> Try using node 15 on CI.

- README.md
I'd like to add this note about the funding from the LibreTexts project that funded my and my students' work over the past couple years.
See https://www2.ed.gov/programs/otp/abstractotp2018.pdf for more info.
> Added acknowledgement to the LibreTexts funding.

- docs/examples/bqplot_example.rst
- docs/examples/ipycytoscape_example.rst
- Removes bqplot warning since pan/zoom now works
- Fixes broken link in ipycytoscape example page
> [DOCS] Update docs

- .github/dependabot.yml
- package.json
- yarn.lock
> [MNT] - bump webpack bundle analyser

- package-lock.json
- packages/core/package.json
- packages/core/src/notebook.ts
- packages/react/.eslintrc
- packages/react/.gitignore
- packages/react/README.md
- packages/react/_tsconfig.json
- packages/react/jest.config.ts
- packages/react/package.json
- packages/react/src/OutputAreaByRef.tsx
- packages/react/src/ThebeCoreProvider.tsx
- packages/react/src/ThebeServerProvider.tsx
- packages/react/src/ThebeSessionProvider.tsx
- packages/react/src/hooks/index.ts
- packages/react/src/hooks/interpolate.ts
- packages/react/src/hooks/notebook.ts
- packages/react/src/index.ts
- packages/react/tests/interpolate.spec.ts
- packages/react/tsconfig.json
- packages/react/tsconfig.test.json
- packages/thebe/package.json
This PR adds some react components, specifically in the form of providers that enable async loading of the `thebe-core` library as well and wrapping core functionality such as:
* Connecting to a ThebeServer
* Starting, accessing and stopping sessions
* Loading, running and executing notebooks via a hook
> Add React Providers and Components

- packages/thebe/src/index.css
> 🔲 remove additional border on outputs

- README.md
@stevejpurves I need your help in getting the thebe docs back up on the new website.
See https://github.com/executablebooks/team-compass/issues/21
> Rebrand to mystmd.org

- .changeset/strong-comics-impress.md
- packages/react/src/ThebeServerProvider.tsx
The `connect` function from the `ThebeServerProvider` now returns the server's ready promise
> 🔌 connect w promise

- packages/core/src/options.ts
- packages/core/src/server.ts
- packages/core/src/sessions.ts
- packages/core/src/types.ts
- packages/core/src/url.ts
- packages/core/tests/config.spec.ts
- packages/core/tests/options.spec.ts
- packages/core/tests/sessions.spec.ts
- packages/core/tests/url.spec.ts
> 🗝 repo providers now make storageKeys

- .changeset/pink-impalas-scream.md
- packages/core/src/types.ts
- packages/react/src/hooks/notebook.ts
Fixes a cross package import from core into react the broke downstream SSR!
> 🛠️ fix/direct import bug

- .changeset/strange-readers-hang.md
- apps/demo-core/src/app.ts
- apps/demo-core/src/setup.ts
- apps/demo-core/static/index.html
- apps/demo-react/src/App.tsx
- apps/demo-react/src/ServerMode.tsx
- apps/simple/static/ipywidgets-local.html
- apps/simple/static/jupyter.html
- apps/simple/static/maths.html
This makes things more secure for users trying things out on local connections.
fixes #631
> ♻️ no more fixed tokens in demos

- .changeset/dull-spiders-walk.md
- packages/core/src/rendermime.ts
> 🎨 add explicit error rendermine factory
