README.md, src/thebelab.js
Added a new optional binderOptions attribute "repoProvider" to specify an alternative provider such as gitlab or git.
Github is still the assumed default and this change does not affect existing installations.
=> Adds support for gitlab and git repositories

README.md, src/thebelab.js
Allows for passing through CodeMirror options specified here: [https://codemirror.net/doc/manual.html#config](https://codemirror.net/doc/manual.html#config)
Allows for enabling options such as readOnly, lineNumbers, and lineWrapping. Personally, I need all of these options for my use case.
closes #97
=> Added option for codeMirrorConfig

docs/conf.py, docs/doc-requirements.txt, docs/index.rst
This updates the requirement for alabaster_jupyterhub to use the right name, it also adds a simple example to the index page so that users can see what thebelab is all about earlier.
=> Updating the requirements for alabaster_jupyterhub

docs/conf.py, docs/index.rst
ReadTheDocs currently doesn't have the example HTML files properly-linked, I think this will fix that. Gonna self merge since this is broken right now
=> adding example html files to static_files so they show up

package-lock.json, package.json
avoids duplicate codemirrors in the bundle when versions don't match exactly
=> rely on @jupyterlab/codemirror to pull in codemirror dependency

src/thebelab.js
This PR removes the / from the .git suffix for the binderUrl. When including the `/` the repository is not recognized, for example by a privately hosted GitLab server.
Now the following config DOES work, while without this PR it does not:
```
binderOptions: {
repoProvider: "git",
repo: "https://gitlab.example.com/user/repo",
ref: "e6c970126f4e819e4a3eb717a86ba9fb5237fde3",
}
```
=> Remove / from .git suffix for binderUrl

src/thebelab.js, webpack.config.js
Change from `Kernel` to `Session` to support the `path` argument.
This adds the ability to specify `path` in `kernelOptions` so the current working directory is changed.
Fixes #114.
=> Add ability to change path for binder

.travis.yml, package.json
some build dependencies have dropped support for node 4
=> drop node 4

package-lock.json, package.json
`html-manager` 0.16, which was added into package.json in #28 is a backward incompatible release.
Updating to this version will require more changes than just updating the package.json.
=> Fixup html-manager version

src/thebelab.js
`widgets.built.css` is the CSS of `@jupyter-widgets/controls` bundled with cssnext, which includes the polyfill for jupyterlab CSS variables (which we use for the classic notebook) and substitutes them by their values in all of the widgets CSS.
This PR makes thebelab use directly the bare CSS making use of the CSS variables that are already on the page in thebelab.
- Note that the tool that was used for this substitution was cssnext which is now deprecated.
- We still produce the old `widgets.built.css` in `@jupyter-widgets/controls` for backward compatibility.
=> Drop cssnext bundle

docs/index.rst
this shouldn't be required (ipykernel or matplotlib bug), but it is. Closes #158
=> add missing %matplotlib inline to docs

docs/howto/initialize_cells.rst, docs/index.rst
This adds a short section describing a few patterns to programmatically run code on a page. It closes #94
=> adding how to section for running code automatically

src/thebelab.js
Use merged options for codemirror to enable user extend the required options. Closes: #168. Seems it Closes: #126 as well.
=> codemirror uses merged options

src/thebelab.js
Skip number to set the mode of the language in Codemirror. Closes #169, Closes #96
=> python mode without number

docs/howto/cm_customize.rst, docs/index.rst
This adds a page to show how to configure codemirror for a page. It is a simple demo that changes the theme for codeMirror.
However, right now it doesn't seem to work! I'm not sure why, so we should figure that out...
=> adding codemirror config page

README.md
The current config doc having only `kernelOptions.name` is a bit confusing. It lets user think that by simply change the name to something like R will enable a R kernel (at least that is what I thought). To run other language, I found that `kernelOptions.kernelName` is what I needed. Including this in the doc I believe will help a lot of people.
The kernelName is passed to @jupyterlab/services and [here](https://github.com/jupyterlab/jupyterlab/blob/37c7a647a1344712c8cf80414db73809f486e766/packages/services/src/session/session.ts#L381) is where kernelName is defined.
=> add kernelName to kernelOptions in README.md

docs/howto/cm_customize.rst, src/thebelab.js
Resolves #190 
Fixes our theme lookup. It also loads theme style as that isn't initially loaded. It only loads the theme that is given in the configuration.
=> Loads CodeMirror Themes

.circleci/config.yml, docs/events.rst, docs/index.rst
This adds a page to discuss events in Thebelab, and how to hook into them.
Also removes CircleCI building for docs so that we can use readthedocs for PR previews
=> adding events docs

docs/Makefile, docs/api.rst, docs/conf.py, docs/contribute.md, docs/doc-requirements.txt, docs/index.rst, docs/package-lock.json, docs/package.json, src/thebelab.js
builds js api docs with jsdoc, just like we have for Python packages with sphinx-autodoc
mostly a placeholder, but good to get started
We need to add jsdoc-style docstrings to our `export function` items in order for them to be available here.
=> [DOC] add jsdoc to sphinx

docs/contribute.md, jupyter-server.js, karma.conf.js, package-lock.json, package.json, test/bootstrap.spec.js, test/sanity.spec.js, test/test_entrypoint.js
Some initial changes to the test setup to help make expanding the test coverage easier and some docs.
Towards issue #228 
Its still not clear how to start the Jupyter Server but have started moving code so that we can test the bootstrap process next.
This could be considered draft until later today, where I will try add some more meaningful tests or if it's blocking someone, this can be brought in. Tests are green and changes I think are positive.
=> Small changes to test setup/layout

docs/contribute.md
There are multiple top-level headers on the "contribute" page. This makes them H2 so that we don't have multiple "titles" for the page.
=> 📚 DOCS: header fix on contribute page

docs/config_reference.rst, docs/configure.rst, docs/events.rst, docs/howto/initialize_cells.rst, docs/minimal_example.rst, docs/package.json, docs/start.rst, examples/README.md, examples/demo.html, examples/index.html, examples/local.html, examples/status_field.html, examples/thebe_status_field.js, examples/widgets.html
This should be a non-invasive change to refresh some of the documentation when referring to Thebe.
I have updated some code, but only comments and strings that have no other effects.
=> 📚 DOCS: Go through docs/strings & change ThebeLab -> Thebe

development.html, src/thebelab.js
This adds functionality to restart and run the kernel. It clears the outputs of each cell with a `"Waiting for kernel ... "` *before* the kernel is restarted (a slight difference from jupyter) but this is helpful as there is no other UI indicator that the button worked.
* I have changed the return of `renderCell` to return `{cell, execute, setOutputText}` which allows you to use them in other contexts.
* There is now a `thebelab.cells` which is an array of the above.
See #237
=> ✨ NEW: Restart and Run All buttons

examples/README.md, examples/index.html, examples/local.html, examples/prompts.html
Another small PR, updating some links to point to the new repository.
See also: #230
=> 📚 DOCS: Update repository urls to point to executable books

src/thebelab.js
This should resolve #224 (we can make a new issue for the persisting kernel (not binder pod) part if needed).
When Binder spawns a pod, the jupyter pod URL and token are saved in the browser's localStorage. When Thebe is activated and there is already a pod URL+token in localStorage, it will try to reuse the existing pod. If it fails, then it falls back to creating a new pod.
=> use localStorage to persist binder pods across pages

src/thebelab.js
This doesn't hook the kernel up again, and only shows an error message. But hey—still better than silently dumping exceptions into the console. :)
=> show an error message when the kernel is dead

docs/configure.rst
- Mentions how read-only can be set as the default in codeMirrorConfig, as well as how to selectively override this using `data-readonly="false"`.
- Swapped some code blocks to `code:: javascript` for better highlighting.
Due to the higher complexity of this scenario, I need others to look this over and ensure it is straight forward and understandable.
Relates to #286 and #274
=> 📚 DOCS: Added language about read-only codeMirror default

README.md, src/thebelab.js
adds binderOptions.savedSession configuration to give users a little control over #266
- toggle behavior off entirely with `savedSession.enabled`
- set max age in seconds with `savedSession.maxAge`
- specify storage prefix with `savedSession.storagePrefix`
and reorganize the code a little bit to make the flow a little easier to manage with all the different stages to abort, including JSON parse errors, etc.
=> ✨ NEW: make savedSession behavior configurable

.github/workflows/test.yml, README.md, package-lock.json, package.json, test/fixtures/HTML/readonly1.html, test/fixtures/HTML/readonly2.html, test/readonly.test.js
Reviewer indicated that the multiple `base-case` tests were confusing and did not improve testing capabilities. The three `base-case` test have been simplified into one test case of `noconfig`.
=> Squash readOnly base-case tests to a single test

docs/examples/bqplot_example.rst
Add note about the pan/zoom button not working to the bqplot documentation.
=> Docs: Add bqplot pan/zoom exception

docs/examples/ipympl_example.rst, docs/index.rst
There is an error I'm running into from using the ipympl github repo as the Binder repo:
Regarding #185 
```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-1-38257e2684a4> in <module>
----> 1 get_ipython().run_line_magic('matplotlib', 'widget')
2 import matplotlib.pyplot as plt
3 fig, ax = plt.subplots()
4 fig.canvas.layout.width = '7in'
5 fig.canvas.layout.height= '5in'
/srv/conda/envs/notebook/lib/python3.7/site-packages/IPython/core/interactiveshell.py in run_line_magic(self, magic_name, line, _stack_depth)
2305                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
2306             with self.builtin_trap:
-> 2307                 result = fn(*args, …
```
=> Add ipympl example documentation

CHANGELOG.md
Regarding #322
According to EBP guidelines, we should keep a changelog for releases. I tried to gather almost all of the PRs from after the last release until now, to hopefully release a new version of Thebe.
I assumed the new version would be 0.6.0 since new features were added, but no breaking incompatibilities with the API were added (if I am looking at them correctly). 
Please feel free to give any feedback on the format or if I missed anything. I excluded the dependency bumps except for the JupyterLab 3.0 API changes and I might go clarify some of the items.
=> NEW: Create changelog, to prepare for a new release

docs/examples/ipympl_example.rst
Removes the code block, which previously removed the `ipympl` directory to run Thebe from the root directory of the repository. I don't think this is necessary anymore thanks to release 0.6.1 at ipympl: https://github.com/matplotlib/ipympl/pull/272
Preview of the new page:
=> 📚 DOCS: Remove unnecessary code block from ipympl doc page

src/thebelab.js
resolves #341 
When kernel is not requested yet, pressing `Restart and Run All` will hang in `Waiting for kernel` forever.
Should go ahead and request a kernel and then run all.
Do not check if kernel exist in `restartAndRunAll()` since it will call `execute()` and that will do the job if a kernel is not there.
=> 🐛 FIX: Should request kernel if needed when restartAndRunAll

docs/examples/ipycytoscape_example.rst
The current repository `QuantStack/ipycytoscape 1.0.4` seems to be broken on the [example page](https://thebelab.readthedocs.io/en/latest/examples/ipycytoscape_example.html) for Thebe. There are errors in console, and the widget does not display. This PR simply bumps the Thebe config in this documentation to a newer version of this repository, `1.2.0`, which I have confirmed works on local HTML pages. This tag runs on jupyterlab3 rather than 2.
=> Ipycytoscape documentation repository --> 1.2.0

docs/examples/ipycytoscape_example.rst
I changed the version for the repository in the regular HTML text but not in the actual configuration which is used for Thebe. This should fix that and make the example page work again.
=> 1.2.0 Thebe config on ipycytoscape doc page

README.md, docs/howto/initialize_cells.rst, examples/README.md
Noticed a missing comma in configuration example. Just to save half a second for the next one who's going to copy/paste it.
=> Make config example parseable

.github/dependabot.yml, package.json, yarn.lock
Recent changes to the package manager introduced an error in the dependabot config file. Apparently `npm` should be used as package manager name for both `npm` and `yarn`. This should fix the last false-positive errors we are seeing in `ci` for depndabot PRs.
NOTE: I have also brought in a version bump to the concurrently dev environment only dependency as part of this PR. Other open dependabot PRs require some more testing.
=> [REF] fix dependabot config

.github/dependabot.yml
Proposal to temporarily disable dependabot and consider dependency upgrades in one go ahead of releases in a more structured way.
=> temporarily disable dependabot

src/render.js
A case issue in code that checks the recently added options to disable the cell buttons, meant that buttons could not be added even when the option was set to true. This has been fixed.
fixes #514
=> [FIX] Run, Restart and RestartRunAll buttons not appearing

docs/contribute.md, docs/index.rst, docs/ui.rst
- Adding a paragraph to explain the keyboard shortcuts now in place for code completion
- fixed two build warnings due to formatting issues in the docs
=> [DOC] code completion

package.json, src/thebelab.js, yarn.lock
This PR includes some isolated local updates matching dependabot alerts that we've seen, but also followed by a full update to all recent minor versions of our dependencies. This should pre-empty any immediate further dependabot alerts and bring us up to date.
This has been tested locally - automation, `yarn develop` environments and with the examples from the docs.
=> 🤖  [MNT] Updating dependencies

packages/react/src/hooks/notebook.ts
The `react` package provides a couple of hooks to help with ThebeNotebooks. One of the hooks dealt wth `ipynb` files (`INotebookContent`) and had been developed further than the second hook that deals with plain code cells as an array of strings.
This PR aligns the base features of the hooks (various execute methods, common approach to ref handling, etc..) which still providing the two different loading methods.
note the original `useNotebookfromSource` has been renamed `useNotebookfromSourceLegacy` and marked as deprecated for now, but users should transition to the new `useNotebookFromSource` (note fixed camel-casing).
=> 🪝hooks aligned for `ipynb` or plain code

packages/core/src/cell.ts, packages/core/src/cell_noexec.ts, packages/core/src/notebook.ts, packages/core/src/types.ts, packages/react/src/hooks/notebook.ts
This PR makes it easier to respond to errors from any cell in a notebook. The IError[] is provided so that can calling page can redisplay or process further as needed.
=> 🛳 exposing any errors during execution in execute return object

packages/core/src/options.ts, packages/core/src/server.ts, packages/core/tests/config.spec.ts, packages/core/tests/options.spec.ts
When `name` is not specified in the `CoreOptions`, the value for `kernelName` will be used before falling back to the default value.
* Addresses #595 for the `0.9.x` todo task
=> 🥅 fallback to `kernelName` when `name` not specified

.changeset/four-bulldogs-judge.md, packages/core/src/cell.ts, packages/core/src/cell_noexec.ts, packages/core/src/index.css, packages/core/src/index.ts, packages/core/src/passive.ts, packages/react/src/hooks/notebook.ts
Changes to the `thebe-core` and `thebe-react` packages to support integration of thebe into the `myst-theme` in [this PR](https://github.com/executablebooks/myst-theme/pull/21).
=> 🧩 Changes to support `myst-theme` integration

.github/workflows/deploy-demo-preview.yml, apps/simple/static/lite.html, package-lock.json, packages/lite/bin/fetchServiceWorker.sh, packages/lite/package.json, packages/lite/src/empty.js, packages/lite/src/index.ts, packages/lite/src/jlite.ts, packages/lite/webpack.config.cjs
The purpose of this PR is to update to using the latest `juptyerlite` codebase, this involves adjusting to the new organisation of the `@juptyerlite/pyodide-kernel` and taking steps to specify the location of the wheels to load. This should be a big improvement over the previous implementation once in place, and the objective is to be able to load the latest wheels from CDN (possibly direct from unpkg.com).
=> use latest Jupyterlite with programatic options

packages/core/src/manager.ts, packages/core/src/passive.ts, packages/core/src/server.ts, packages/core/src/session.ts, packages/core/src/types.ts, packages/react/src/ThebeServerProvider.tsx, packages/react/src/ThebeSessionProvider.tsx
change to enable better shutdown and disposal of resources from react components
=> 🗑 feat/dispose cycles

apps/docs-core/thebe-docs.md, apps/simple/static/index.html, apps/simple/static/lite.html, apps/simple/static/main.css, packages/thebe/package.json, packages/thebe/src/codemirror.ts, packages/thebe/src/index.css, packages/thebe/src/options.ts, packages/thebe/src/render.ts, packages/thebe/src/thebe.ts, packages/thebe/src/types.ts
This PR is work towards fixing syntax highlighting, mode selection and theming which will impact on the following issues:
Useful reference for theme changes: https://codemirror.net/5/demo/theme.html#darcula
We should also tackle this here: 
it's in theory a breaking change to API but no-one can be relying on these options anyway.
=> 📡 autoload mode and strip back bundled css classes and overrides

.changeset/nice-brooms-fly.md, apps/demo-core/package.json, apps/simple/static/index.html, apps/simple/static/ipywidgets-lite.html, apps/simple/static/lite.html, package-lock.json, packages/lite/package.json, packages/lite/webpack.config.cjs, packages/react/src/ThebeServerProvider.tsx
Because this came out  recently. Note that upgrading here really only means two things:
* We bump the version in our dependency list so that the right wheels get bundled into the `dist` folder for convenience
* We update the demos and `thebe-react` to use the CDN urls for the latest version
Beyond that the actual version of the `pyodide-kernel` is completely configurable at runtime, provided is maintains compatibility with the `JuypetrLiteServer` version in use.
(Note: this is something that can be improved and documented)
=> 🆙 upgrade to `pyodide-kernel@0.0.8`

apps/demo-react/public/index.html, apps/demo-react/src/App.tsx, apps/demo-react/src/ServerMode.tsx, apps/demo-react/src/ThebeStatusTray.tsx, packages/core/src/options.ts, packages/core/tests/config.spec.ts, packages/core/tests/connect.binder.spec.ts, packages/core/tests/options.spec.ts
fixes and improvements so that the react demo can be a better start example
=> 🛠 fix/react demo

apps/docs-core/react-lite.md, packages/core/README.md, packages/core/bin/copy-thebe-assets.cjs, packages/core/package.json, packages/lite/README.md
Added the `copy-thebe-assets` script and referenced it in the relevant docs.
This resolves #645 
If I am understanding correctly this stage is required whenever using either `thebe-lite` or `thebe-core`,  so I put the script in `thebe-core`.
I have also made it optional to have `thebe-lite` installed but later I saw the it is a dependency of `thebe-core` which makes this change kinda moot
=> docs update : Installation copy-assets script

.changeset/great-vans-flow.md, packages/core/src/cell.ts, packages/core/src/cell_noexec.ts, packages/core/src/notebook.ts, packages/core/src/passive.ts, packages/core/src/session.ts, packages/core/src/types.ts
Some ongoing work to support integration of `thebe` in the `myst-theme`. The purpose of this PR is to extend `core` and `react` further to support more stateful use of `thebe` in applications. For example, being able to maintain multiple kernels/sessions on a server and navigate between pages that use them while maintaining consistent state in the DOM.
See https://github.com/executablebooks/myst-theme/pull/136 for the work driving these changes.
=> make cells more stateful

.changeset/small-glasses-fold.md, packages/core/package.json, packages/lite/package.json, packages/react/package.json, packages/thebe/package.json
...currently consumers see missing file errors in their development environments.
=> 🐿 ship sources for sourcemaps

.changeset/heavy-ravens-crash.md, packages/lite/src/jlite.ts, packages/lite/src/service-worker.js, packages/lite/webpack.config.cjs
added a reduced version of the jupyterlite service worker and build config to include it by default. This version should do no caching and only handle the braodcast messaging needed by jupyterlite.
addresses #688
=> 🧑🏾‍🏭 override default jupyterlite service worker

.changeset/new-spoons-divide.md, apps/demo-react/src/AdminPanel.tsx, apps/demo-react/src/NotebookPage.tsx, packages/core/src/server.ts
This was uncaught during recent dependency upgrades, where `server.listRunningSessions` would throw and exception due to buffer overrun, as we were not handling the iterator result properly.
=> 🛠 fix list running sessions

packages/core/src/server.ts, packages/react/src/hooks/notebook.ts
unhandled exceptions could occur because of session manager not being ready when we should await it
=> 🕰 await session manager and move exception

.changeset/pink-seahorses-smell.md, packages/core/src/sessions.ts, packages/core/tests/sessions.spec.ts
This solves an issue where because of additional query params that vary independent of the session e.g. signed urls or auth tokens, the saved session would not be found and a new server would be started.
=> 🧹 using origin and pathname only for key

apps/docs/ui.rst, packages/thebe/src/options.ts, packages/thebe/src/render.ts
mountRunAllButton has uppercase All, make consistent.
=> Inconsistent capitalization: mountRestartallButton

.changeset/purple-queens-breathe.md, .gitignore, packages/core/src/server.ts
This fixes: https://github.com/executablebooks/myst-theme/issues/394 in the short term, this fix as valid as there is no filesystem support enabled in `thebe-lite` yet.
=> 🍽️ lite doesn't respect paths

packages/thebe/src/codemirror.ts
hey y'all, i figured i'd kick off this discussion with a pull request instead of an issue. i'm proposing to add support for the <kbd>Esc</kbd>. currently, thebe violates  [Success Criterion 2.1.2 (No Keyboard Trap)](https://www.w3.org/TR/2008/REC-WCAG20-20081211/#keyboard-operation-trapping). this pull request applies technique [G21: Ensuring that users are not trapped in content](https://www.w3.org/WAI/GL/2010/WD-WCAG20-TECHS-20100708/G21) so that when `Esc` is pressed we use `cm.display.input.blur()` to remove focus from the editor allowing keyboard users to continue through their natural tab order.
i'm not really great at js development or testing so i'd appreciate any pointers to cleaning up the pr.
=> remediate wcag 2.1.2 - no keyboard trap

.changeset/selfish-boats-rhyme.md, packages/react/src/ThebeServerProvider.tsx, packages/react/src/ThebeSessionProvider.tsx
=> ⚙️ enable server re-configuration

.changeset/lovely-roses-dance.md, .changeset/selfish-feet-travel.md, apps/simple/static/index.html, apps/simple/static/ipywidgets-lite.html, apps/simple/static/lite.html, package-lock.json, packages/lite/package.json, packages/lite/src/jlite.ts, packages/lite/src/types.ts, packages/react/src/ThebeServerProvider.tsx
This PR does 2 things:
* Upgrade to the latest JupyterLite dependencies, to consume a fix to #771.
* `thebe-lite` now sets default `litePluginSettings` in alignment with the bundled `pyodide-kernel` version. This simplifies usage and upgrades for clients who no longer need to keep this  setting in sync with the package. An improvement pending dynamic loading.
=> Fix widgets disconnect
